name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: admin123
          POSTGRES_USER: root
          POSTGRES_DB: simple_bank
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    environment: Development
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Install golang-migrate
      run: |
        curl -s https://packagecloud.io/install/repositories/golang-migrate/migrate/script.deb.sh | sudo bash
        sudo apt-get install migrate

    - name: Migrate Database Up
      run : make migrateup

    - name: Create app.env file
      run: |
        echo "DB_DRIVER=${{ secrets.DB_DRIVER }}" >> app.env
        echo "DB_SOURCE=${{ secrets.DB_SOURCE }}" >> app.env
        echo "SERVER_ADDRESS=${{ secrets.SERVER_ADDRESS }}" >> app.env
        echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> app.env

    - name: Test
      run: make test